config/routes.rb
Taskdeck::Application.routes.draw do

  resources :users
  resources :sessions, only: [:create, :new, :destroy] 
  resources :organizations 
  resources :teams
  resources :tasks
  resources :task_notes
  resources :reminders
  resources :projects
  resources :project_tasks

  root to: 'static_pages#home'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'
  match '/neworg', to: 'organizations#new'
  match '/join', to: 'organizations#join'
  match '/joinorg', to: 'organizations#joinorg'
  match '/teampanel', to: 'teams#teampanel'
  match '/newteam', to: 'teams#new'
  match '/orgpanel', to: 'organizations#orgpanel'
  match '/jointeam', to: 'users#jointeam'
  match '/confirmteam', to: 'users#confirmteam'
  match '/denyteam', to: 'users#denyteam'
  match '/removeuserteam', to: 'users#removeuserteam'
  match '/deleteteam', to: 'teams#deleteteam'
  match '/newtask', to: 'tasks#new'
  match '/team_management', to: 'teams#team_management'
  match '/member_tasks', to: 'teams#member_tasks'
  match '/approvetask', to: 'tasks#approvetask'
  match '/rejecttask', to: 'tasks#rejecttask'
  match '/completetask', to: 'tasks#completetask'
  match '/updatetask', to: 'tasks#updatetask'
  match '/finished', to: 'tasks#finished'
  match '/pending', to: 'tasks#pending'
  match '/update', to: 'tasks#updateform'
  match '/newnote', to: 'task_notes#new_note'
  match '/clearnotifs', to: 'notifications#clearnotifs'
  match '/notifications', to: 'notifications#index'
  match '/settings', to: 'users#edit'
  match '/assigntask', to: 'tasks#assigntaskform'
  match '/assigntask2', to: 'tasks#assigntask'
  match '/assignprojectask', to: 'project_tasks#assigntask'  
  match '/completeprojecttask', to: 'project_tasks#completetask'
  match '/updateptaskform', to: 'project_tasks#updateform'
  match '/updateptask', to: 'project_tasks#updatetask'
  match '/admin', to: 'organizations#admin'
  match '/updateprefs', to: 'organizations#updateprefs'
  match '/updatepassword', to: 'organizations#updatepassword'

  match '/updateproject', to: 'projects#updateproject'
  match '/resetorgpassword', to: 'organizations#resetpassword'
  match '/resetuserpassword', to: 'users#resetpassword'
  match '/forgotpassword', to: 'users#forgotpassword'
  match '/invite', to: 'users#invite'

  match '/about', to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_for_new_organization.html.erb
<% if @organization.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@organization.errors.count, "error") %>.
    </div>
    <ul>
    <% @organization.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_for_new_task.html.erb
<% if @task.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@task.errors.count, "error") %>.
    </div>
    <ul>
    <% @task.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_for_new_task_note.html.erb
<% if @tasknote.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@tasknote.errors.count, "error") %>.
    </div>
    <ul>
    <% @tasknote.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_for_new_team.html.erb
<% if @team.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@team.errors.count, "error") %>.
    </div>
    <ul>
    <% @team.errors.full_messages.each do |msg| %>
      <li> <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_no_organization.html.erb
Welcome to TaskDeck! It seems that you are currently not in any company, group, or organization! You must create one or join one in order to use TaskDeck.
<br />
<br />

<div class="span4 offset1">
<p>Would you would like to create a TaskDeck for your organization? If you are an administrator or manager of your organization, this should be the option for you. 
  <br />
  <br />
  <br />
  <a button class="btn btn-large" href="/neworg">Create TaskDeck</button></a>
</p>
</div>

<div class="span4 offset1">
<p>If a TaskDeck already exists for your company/organization/group, enter the name and passcode of your organization in order to join it. 
  <br />
  <br />
    <br />
  <br />

  <a button class="btn btn-large" href="/join">Join Organization</button></a>
</div>


<br />
<br />
<br />
<br />
<br />
<br />

app/views/shared/_not_signed_in.html.erb
<div class="modal hide fade" id="Signin">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Sign In</h3>
  </div>
  <div class="modal-body">
    <%= form_for(:session, url: sessions_path) do |f| %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <br />

    <p>New user? <%= link_to "Sign up now!", signup_path %></p>
    <p><a data-toggle="modal" href="#ForgotPassword" >Forgot your password?</a></p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn pull-left" data-dismiss="modal">Close</a>
      <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>


<div class="modal hide fade" id="ForgotPassword">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">×</button>
    <h3>Reset Password</h3>
  </div>
  <div class="modal-body">
      <%= form_for :user, :url => url_for(:controller => 'users', 
                            :action => 'forgotpassword') do |f| %>

      <%= f.label :email, "Enter the email address of your TaskDeck account:" %>
      <%= f.text_field :email %>


      <br />
      <p>Password reset instructions will be sent to you via email.</p>

  </div>
  <div class="modal-footer">
    <a href="#" class="btn pull-left" data-dismiss="modal">Close</a>
      <%= f.submit "Reset Password", class: "btn btn-large btn-primary" %>
    <% end %>

  </div>
</div>




<div class="hero-unit">
  <h1>TaskDeck</h1>
  <p>A simple and clean way to manage the people and teams of your small organization or company. No clutter, with a simple work-focused design.</p>
  <p>
    <a class="btn btn-primary btn-large" href="/signup">
      Sign Up!
    </a>
  </p>
</div>

app/views/shared/_side_menu.html.erb
    <div class="well">

      <section>
        <h3><%= current_user.name %></h3> 
        <strong>
          <%= current_user.email %><br />
          <% if !current_user.team_id.nil? %>
            <%= current_user.team.name %><br />
          <% end %>
          <%= current_user.organization.full_name %><br />
        </strong>
      </section>
      <br />
      <br />


      <section>
        <ul class="nav nav-list">
          <li class="nav-header">
            Menu
          </li>
          <% if @active == 1 %>
          <li class="active">
          <% else %>
          <li>
          <% end %>
            <a href="/">
            <i class="icon-home"></i>
              TaskDeck
            </a>
          </li>


          <% if @active == 2 %>
          <li class="active">
          <% else %>
          <li>
          <% end %>
            <a href="/teampanel">
            <i class="icon-user"></i>
              Team Panel
            </a>
          </li>



          <% if @active == 3 %>
          <li class="active">
          <% else %>
          <li>
          <% end %>
            <a href="/orgpanel">
            <i class="icon-briefcase"></i>
              <%= current_user.organization.full_name %>
            </a>
          </li>




          <% if @active == 4 %>
          <li class="active">
          <% else %>
          <li>
          <% end %>
            <a href="/settings">
            <i class="icon-wrench"></i>
              Settings
            </a>
          </li>

          <% if current_user.admin %>
          <% if @active == 5 %>
          <li class="active">
          <% else %>
          <li>
          <% end %>
            <a href="/admin">
            <i class=" icon-cog"></i>
              Admin Panel
            </a>
          </li>
          <% end %>
        </ul>
      </section>
</div>